# Model configuration file
tabnet:
  n_d: 32
  n_a: 32
  n_steps: 5
  gamma: 1.3
  lambda_sparse: 1e-3
  max_epochs: 100
  batch_size: 256
  patience: 20

random_forest:
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 'sqrt'
  random_state: 42

xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

svm:
  kernel: 'rbf'
  C: 1.0
  gamma: 'scale'
  probability: true
  random_state: 42
